language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: jqTeUsToSomwxZOcJuJPyKm4Cz/+1yh8s9fHRNlOCoxvBk28zTFaJ9dutf+ojmiXlFVBYq9ZPtVRKPXs0C/SsORJTJlWXPvCrhmjELFin58srW/W2KtDmfu92BJvItxOr7B3J8E3BdeWBn+he+qcd+QXGQM6OAEtsKfTW2Y8/T72ShOjgFjpyGwHhCK+sEnXTZ479Dx9b1kYeTnytXqw1oWZZeaCfKKF3OVk2UmwjvffbCdXUuaXBNMH8WAyyh1c8fms8i/iscqe2B0y78liXzGQd1huYl84huCbUtuFu4SD14IuaEj8psCv8SP0hWP14uVV+PBIHo65Xp69yl+Zr//oh0h69wtyslzuP+ShSCh98swH3NpfVxnsw77+Jo+IHytnjpKx3lteEeRWLizfUTPdJ8qqJ/NAREOunsiE5dl8iNMewzcm1U5j24Qzagq29sLRctO9z/LZHLd4L9VVRlKXvyZucjVsRnSdZTCoD69ncpJEggK4xZURpadtctpilPDsUX/u5F0zAdMX8yQDBwn3Tu9YeHXA552I5kdb5hi2PYEeBinFlC9eQD1GXqk/I8gunUqasebG0Cb/RdioqutjIBt+rFAswbzxhR7CJu4AJFLrP5htEaChl89qYYoX7yd6kF/HqgqxTBWUKmuid3TQRxZmEDID6U5uUQwWNxk=
  app: floating-oasis-14197
  on:
    repo: tcw5038/BlogAPI
